app:
# TOKEN EXPIRATION
  token:
    secretkey: S0g0f0Rc3
    expiration: 86400000 # One day (24 hours) in milliseconds
  refreshtoken:
    expiration: 172800000 # Two days (48 hours) in milliseconds

server:
  port: 9000

spring:
  application:
    name: api-server
  datasource:
    url: jdbc:postgresql://postgresql_service:5432/minicourses
    username: sogo
    password: sogochallenge123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    out-of-order: true