server:
  port: 9000

spring:
  application:
    name: api-server
  datasource:
    url: jdbc:postgresql://localhost:5432/minicourses
    username: sogo
    password: sogochallenge123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      #      Enabled only to generate table and database stuffs
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    # disable when use hibernate only
    enabled: false